/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicauca.microkernel.restaurante.core.app;
import co.edu.unicauca.microkernel.restaurante.core.access.Factory;
import co.edu.unicauca.microkernel.restaurante.core.services.ComponenteService;
import static co.edu.unicauca.microkernel.restaurante.core.services.Messages.successMessage;
import co.edu.unicauca.microkernel.restaurante.commons.entities.Componente;
import co.edu.unicauca.microkernel.restaurante.commons.interfaces.IComponenteRepository;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author SoftwareTeam
 */
public class AdminCompo extends javax.swing.JFrame {

    /**
     * Creates new form AdminAlmuerzo
     */
    public AdminCompo() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Administrador Componentes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarAlm = new javax.swing.JButton();
        lblAddComp = new javax.swing.JLabel();
        btnMostrarComp = new javax.swing.JButton();
        txtIdComp = new javax.swing.JTextField();
        txtNombreComp = new javax.swing.JTextField();
        btnAgregarComp = new javax.swing.JButton();
        cbTipoComp = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAdmi = new javax.swing.JLabel();
        imgContacto1 = new javax.swing.JLabel();
        btnContacto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo restaurante esquina.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, 70));

        btnAgregarAlm.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        btnAgregarAlm.setForeground(new java.awt.Color(153, 0, 0));
        btnAgregarAlm.setText("Añadir Almuerzo");
        btnAgregarAlm.setBorder(null);
        btnAgregarAlm.setBorderPainted(false);
        btnAgregarAlm.setContentAreaFilled(false);
        btnAgregarAlm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlmActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarAlm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 120, 30));

        lblAddComp.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        lblAddComp.setForeground(new java.awt.Color(153, 0, 0));
        lblAddComp.setText("Agregar componentes");
        getContentPane().add(lblAddComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 390, 40));

        btnMostrarComp.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        btnMostrarComp.setForeground(new java.awt.Color(153, 0, 0));
        btnMostrarComp.setText("Mostrar Componentes");
        btnMostrarComp.setBorder(null);
        btnMostrarComp.setBorderPainted(false);
        btnMostrarComp.setContentAreaFilled(false);
        btnMostrarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCompActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 170, 30));
        getContentPane().add(txtIdComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 130, 30));
        getContentPane().add(txtNombreComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 30));

        btnAgregarComp.setBackground(new java.awt.Color(102, 0, 0));
        btnAgregarComp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnAgregarComp.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarComp.setText("Agregar componente");
        btnAgregarComp.setBorder(null);
        btnAgregarComp.setBorderPainted(false);
        btnAgregarComp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregarComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCompActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, 30));

        cbTipoComp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cbTipoComp.setForeground(new java.awt.Color(153, 0, 51));
        cbTipoComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Principio", "Bebida" }));
        getContentPane().add(cbTipoComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 120, 30));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("Tipo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 80, 30));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Nombre:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 80, 20));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Id:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 80, 20));

        lblAdmi.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        lblAdmi.setForeground(new java.awt.Color(153, 0, 0));
        lblAdmi.setText("Administrador");
        getContentPane().add(lblAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, 30));

        imgContacto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cc.png"))); // NOI18N
        getContentPane().add(imgContacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 40, 20));

        btnContacto.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnContacto.setText("Contactanos");
        btnContacto.setBorder(null);
        btnContacto.setBorderPainted(false);
        btnContacto.setContentAreaFilled(false);
        btnContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactoActionPerformed(evt);
            }
        });
        getContentPane().add(btnContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        btnSalir.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 60, 30));

        lblFondo.setFont(new java.awt.Font("Calibri Light", 1, 16)); // NOI18N
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Base2.png"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarAlmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlmActionPerformed
        AdminAlmuerzo adalmu = null;
        try {
            adalmu = new AdminAlmuerzo();
        } catch (Exception ex) {
            Logger.getLogger(AdminCompo.class.getName()).log(Level.SEVERE, null, ex);
        }
        adalmu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarAlmActionPerformed

    private void btnMostrarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCompActionPerformed
        Admin admin = new Admin();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMostrarCompActionPerformed

    private void btnAgregarCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCompActionPerformed
        // TODO add your handling code here:
        int Idtipocomponente;
        IComponenteRepository service= Factory.getInstance().getRepositoryComponente();
        
        ComponenteService componenteService= new ComponenteService(service);
        Idtipocomponente = TipoComponente();
        Componente componente = new Componente();
        
        componente.setIdComponente(Integer.parseInt(txtIdComp.getText()));
        componente.setIdRestaurante(1); //revisar para enviar el id restaurante 
        componente.setNombreComponente(txtNombreComp.getText());
        componente.setTipoComponente(cbTipoComp.getSelectedItem().toString());
        componente.setIdtipoComponente(Idtipocomponente);
        
        try {
            String response = componenteService.contarComponentex(componente.getIdComponente(), componente.getNombreComponente());
            if (response.equals(1+"") || response.equals(2+"")){
                successMessage("Id o el nombre del componente ya existe ", "Error");
                clearCotronls();
            }
            else{
                String response2 = componenteService.createComponente(componente);
                successMessage("Componente " + response2 + " agregado con exito.", "Atención");
                clearCotronls();   
            }           
             
        } catch (Exception ex) {
                System.out.println(ex);
                successMessage(ex.getMessage() + "Error Id existente y/o Componente ", "Atención");
        }
    }                                           
    private void clearCotronls() {
        txtIdComp.setText("");
        txtNombreComp.setText("");
    }
    private int TipoComponente(){
        if(cbTipoComp.getSelectedItem().toString() == "Entrada")
            return 1;
        if(cbTipoComp.getSelectedItem().toString() == "Principio")
            return 2;
        if(cbTipoComp.getSelectedItem().toString() == "Proteína")
            return 3;
        if (cbTipoComp.getSelectedItem().toString() == "Bebida")
            return 4;
        return 0;
    }//GEN-LAST:event_btnAgregarCompActionPerformed

    private void btnContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactoActionPerformed
        // TODO add your handling code here:
        Contacto cont = new Contacto(4);
        cont.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnContactoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
         //resp =0 si, resp = 1 no.
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp==0){
        Login log = new Login();
        log.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCompo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCompo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCompo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCompo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCompo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlm;
    private javax.swing.JButton btnAgregarComp;
    private javax.swing.JButton btnContacto;
    private javax.swing.JButton btnMostrarComp;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbTipoComp;
    private javax.swing.JLabel imgContacto1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddComp;
    private javax.swing.JLabel lblAdmi;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtIdComp;
    private javax.swing.JTextField txtNombreComp;
    // End of variables declaration//GEN-END:variables
}
